# -*- mode: ruby -*-
# vi: set ft=ruby :
HOSTNAME_VM="Test"
CPU=1
MEM=1024

Vagrant.configure("2") do |config|
    config.vm.box = "generic/rocky8"
    config.vm.box_version = "4.3.12"
    config.vm.box_check_update = false
    config.vm.hostname = HOSTNAME_VM
    config.vm.synced_folder ".", "/vagrant", disabled: false
    config.vbguest.auto_update = false
    
    config.ssh.insert_key = false
    config.ssh.password = "Vagrant"
    
    config.vm.provider "virtualbox" do |vbox, override|
	vbox.name = "TestVM"
	vbox.cpus = CPU
	vbox.memory = MEM
	vbox.gui = false
        vbox.linked_clone = false
    end

    config.vm.provider "libvirt" do |kvm, override|
	kvm.title = "TestVM"
	kvm.cpus = CPU
	kvm.memory = MEM
	kvm.cputopology :sockets => '1', :cores => CPU, :threads => '1'
    end

  config.vm.provider "vmware_desktop" do |vmw, override|    
      vmw.vmx['displayname'] = "TestVM"
      vmw.vmx["numvcpus"] = CPU
      vmw.vmx["memsize"] = MEM
      vmw.vmx["cpuid.coresPerSocket"] = "1"
      vmw.gui = false
      vmw.linked_clone = false
  end

    #config.vm.provision "global", type: "shell", run: "once", path: "provisioning/bootstrap.sh"
end

