# -*- mode: ruby -*-
# vi: set ft=ruby :
# Preguntar
# require_relative 'provisioning/vbox.rb'
# VBoxUtils.check_version('7.1.6')
# Vagrant.require_version ">= 2.4.3"


HOSTNAME_VM="Manddddager-API"
CPU=1
MEM=1024

Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/precise64"
  config.vm.box_check_update = false
  config.vm.hostname = HOSTNAME_VM

  # Configure hostmanager and vbguest plugins
  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  config.hostmanager.manage_guest = true
  config.vbguest.auto_update = false

  config.vm.provider "virtualbox" do |vbox,  override|
      vbox.name = "TFGdafdasf-VM-API"
      vbox.cpus = CPU
      vbox.memory = MEM
      vbox.gui = false
  end
end
